name: Create SC
description: Tạo một SC
title: "Quản lý đào tạo tập trung toàn bộ trung tâm"
labels: ["SC"]

body:
  - type: input
    id: uc_id
    attributes:
      label: ID UC
      placeholder: UC-01: đăng ký khóa học
    validations:
      required: true

  - type: input
    id: sc_id
    attributes:
      label: ID SC
      placeholder: SC-01-01
    validations:
      required: true
