name: Create Feat
description: Functional behavior of the system (use case)
title: "Đăng ký khóa học trực tuyến"
labels: ["UC"]

body:
  - type: input
    id: uc_id
    attributes:
      label: ID UC
      placeholder: UC-01
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Tên UC
      placeholder: Đăng ký khóa học trực tuyến
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Mô tả
      placeholder: Học viên hoặc phụ huynh đăng ký tham gia khóa học trực tuyến. Hệ thống kiểm tra điều kiện và ghi nhận đăng ký.
    validations:
      required: true

  - type: textarea
    id: Basic Flow
    attributes:
      label: Basic Flow
      placeholder:
        1. Học viên/Phụ huynh đăng nhập hệ thống. 
        2. Chọn khóa học từ danh sách mở đăng ký.
        3. Xem thông tin chi tiết khóa học. 
        4. Xác nhận đăng ký và điền thông tin bổ sung.
        5. Hệ thống kiểm tra điều kiện (trình độ, sĩ số lớp).
        6. Ghi nhận đăng ký và cập nhật danh sách lớp.
        7. Gửi thông báo xác nhận qua email/app.
    validations:
      required: true

  - type: textarea
    id: Alternative Flows
    attributes:
      label: Alternative Flows
      placeholder:
          2.2.1 Lớp học đã đầy sĩ số
         • Hệ thống đề xuất lớp thay thế cùng khóa học.
         • Học viên/Phụ huynh chọn lớp mới hoặc hủy.
         2.2.2 Hồ sơ chưa hợp lệ 
        • Yêu cầu cập nhật hồ sơ (thiếu thông tin, tuổi không phù hợp).
         • Sau khi cập nhật → quay lại bước 5.
    validations:
      required: true

  - type: textarea
    id: Special Requirements
    attributes:
      label: Special Requirements
      placeholder:
        - Bảo mật thông tin cá nhân theo Luật Bảo vệ Dữ liệu.
        - Thời gian xử lý đăng ký < 3 giây. 
        - Form responsive trên mobile/desktop.
    validations:
      required: true

  - type: textarea
    id: PreConditions
    attributes:
      label: PreConditions
      placeholder:
        - Đã đăng nhập hệ thống.
        - Có khóa học đang mở đăng ký.
    validations:
      required: true

  - type: textarea
    id: PostConditions
    attributes:
      label: PostConditions
      placeholder:
        - Đăng ký được ghi nhận. 
        - Học viên được thêm vào lớp hoặc danh sách chờ. 
        - Thông báo xác nhận được gửi.
    validations:
      required: true

  - type: textarea
    id: Extension Points
    attributes:
      label: Extension Points
      placeholder: 6.1 Thanh toán đăng ký (sau bước 6 nếu khóa học yêu cầu thanh toán trước).
    validations:
      required: true
